"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Tuple
from numpy import generic
from numpy.typing import NDArray

__all__: list[str]
def byte_bounds(a: generic | NDArray[Any]) -> tuple[int, int]:
    ...

def normalize_axis_tuple(axis: int | Iterable[int], ndim: int = ..., argname: None | str = ..., allow_duplicate: None | bool = ...) -> Tuple[int, int]:
    ...

def normalize_axis_index(axis: int = ..., ndim: int = ..., msg_prefix: None | str = ...) -> int:
    ...

