"""
This type stub file was generated by pyright.
"""

from typing import Any, Protocol, TypeVar

_T_contra = TypeVar("_T_contra", contravariant=True)
class _SupportsWrite(Protocol[_T_contra]):
    def write(self, s: _T_contra, /) -> Any:
        ...
    


__all__: list[str]
def get_include() -> str:
    ...

def info(object: object = ..., maxwidth: int = ..., output: None | _SupportsWrite[str] = ..., toplevel: str = ...) -> None:
    ...

def source(object: object, output: None | _SupportsWrite[str] = ...) -> None:
    ...

def show_runtime() -> None:
    ...

